// ==============================================================
// GZW TACTICAL TOOL - COMPLETE ITEM IMAGE DATABASE
// ==========================================
// Anleitung: Lade die Bilder herunter, benenne sie EXAKT wie die 
// Wörter auf der linken Seite (inklusive .png) und lade sie in "images".

const imageBaseUrl = "https://raw.githubusercontent.com/Toxikologe/gzw-tool/main/images/";

const itemImages = {
    // ==========================================
    // 1. WAFFEN (WEAPONS)
    // ==========================================
    "m4a1": imageBaseUrl + "m4a1.png",
    "m16a1": imageBaseUrl + "m16a1.png",
    "m201c": imageBaseUrl + "m201c.png",
    "cqa1": imageBaseUrl + "cqa1.png",
    "ddm4": imageBaseUrl + "ddm4.png",
    "ks1": imageBaseUrl + "ks1.png",
    "sicmcx": imageBaseUrl + "sicmcx.png",
    "mk18": imageBaseUrl + "mk18.png",
    "ak74": imageBaseUrl + "ak74.png",
    "ak74n": imageBaseUrl + "ak74n.png",
    "ak74m": imageBaseUrl + "ak74m.png",
    "aks74u": imageBaseUrl + "aks74u.png",
    "aks74un": imageBaseUrl + "aks74un.png",
    "akm": imageBaseUrl + "akm.png",
    "akmn": imageBaseUrl + "akmn.png",
    "akms": imageBaseUrl + "akms.png",
    "akmsn": imageBaseUrl + "akmsn.png",
    "ak101": imageBaseUrl + "ak101.png",
    "ak102": imageBaseUrl + "ak102.png",
    "ak103": imageBaseUrl + "ak103.png",
    "ak104": imageBaseUrl + "ak104.png",
    "ak105": imageBaseUrl + "ak105.png",
    "ak12": imageBaseUrl + "ak12.png",
    "ak15": imageBaseUrl + "ak15.png",
    "ak19": imageBaseUrl + "ak19.png",
    "ak308": imageBaseUrl + "ak308.png",
    "vz58": imageBaseUrl + "vz58.png",
    "vz58v": imageBaseUrl + "vz58v.png",
    "typ56": imageBaseUrl + "typ56.png",
    "typ56_1": imageBaseUrl + "typ56_1.png",
    "typ56_2": imageBaseUrl + "typ56_2.png",
    "m14": imageBaseUrl + "m14.png",
    "m14ebr": imageBaseUrl + "m14ebr.png",
    "m1a": imageBaseUrl + "m1a.png",
    "m700": imageBaseUrl + "m700.png",
    "rem788": imageBaseUrl + "rem788.png",
    "mosin": imageBaseUrl + "mosin.png",
    "mosin_sniper": imageBaseUrl + "mosin_sniper.png",
    "mosin_obrez": imageBaseUrl + "mosin_obrez.png",
    "svd": imageBaseUrl + "svd.png",
    "svds": imageBaseUrl + "svds.png",
    "sks": imageBaseUrl + "sks.png",
    "op_sks": imageBaseUrl + "op_sks.png",
    "mp7a1": imageBaseUrl + "mp7a1.png",
    "mp7a2": imageBaseUrl + "mp7a2.png",
    "mp5a2": imageBaseUrl + "mp5a2.png",
    "mp5a3": imageBaseUrl + "mp5a3.png",
    "mp5sd": imageBaseUrl + "mp5sd.png",
    "mp5k": imageBaseUrl + "mp5k.png",
    "vityaz": imageBaseUrl + "vityaz.png",
    "vz61": imageBaseUrl + "vz61.png",
    "m870": imageBaseUrl + "m870.png",
    "moss590": imageBaseUrl + "moss590.png",
    "moss590a1": imageBaseUrl + "moss590a1.png",
    "moss590_shock": imageBaseUrl + "moss590_shock.png",
    "alien": imageBaseUrl + "alien.png",
    "glock17": imageBaseUrl + "glock17.png",
    "glock19": imageBaseUrl + "glock19.png",
    "m9a1": imageBaseUrl + "m9a1.png",
    "m9a3": imageBaseUrl + "m9a3.png",
    "1911": imageBaseUrl + "1911.png",
    "ccc": imageBaseUrl + "ccc.png",
    "makarov": imageBaseUrl + "makarov.png",
    "makarov_pb": imageBaseUrl + "makarov_pb.png",
    "typ51": imageBaseUrl + "typ51.png",

    // ==========================================
    // 2. MODS & ATTACHMENTS
    // ==========================================
    "m_nt4": imageBaseUrl + "m_nt4.png",
    "m_rc1": imageBaseUrl + "m_rc1.png",
    "m_rc2": imageBaseUrl + "m_rc2.png",
    "m_pbs1": imageBaseUrl + "m_pbs1.png",
    "m_pbs4": imageBaseUrl + "m_pbs4.png",
    "m_tgpv": imageBaseUrl + "m_tgpv.png",
    "m_banish": imageBaseUrl + "m_banish.png",
    "m_srd762": imageBaseUrl + "m_srd762.png",
    "m_salvo": imageBaseUrl + "m_salvo.png",
    "m_rotex": imageBaseUrl + "m_rotex.png",
    "m_comp": imageBaseUrl + "m_comp.png",
    "m_dtk1": imageBaseUrl + "m_dtk1.png",
    "m_dtk2": imageBaseUrl + "m_dtk2.png",
    "m_hyper": imageBaseUrl + "m_hyper.png",
    "m_9mm": imageBaseUrl + "m_9mm.png",
    "o_exps": imageBaseUrl + "o_exps.png",
    "o_t2": imageBaseUrl + "o_t2.png",
    "o_kobra": imageBaseUrl + "o_kobra.png",
    "o_specter": imageBaseUrl + "o_specter.png",
    "o_vudu1": imageBaseUrl + "o_vudu1.png",
    "o_vudu3": imageBaseUrl + "o_vudu3.png",
    "o_razor": imageBaseUrl + "o_razor.png",
    "o_viper": imageBaseUrl + "o_viper.png",
    "o_acog": imageBaseUrl + "o_acog.png",
    "o_pso1": imageBaseUrl + "o_pso1.png",
    "o_pu": imageBaseUrl + "o_pu.png",
    "g_rvg": imageBaseUrl + "g_rvg.png",
    "g_shift": imageBaseUrl + "g_shift.png",
    "g_rk2": imageBaseUrl + "g_rk2.png",
    "g_bcm": imageBaseUrl + "g_bcm.png",
    "g_rk3": imageBaseUrl + "g_rk3.png",
    "s_pt1": imageBaseUrl + "s_pt1.png",
    "s_pt3": imageBaseUrl + "s_pt3.png",
    "s_zhukov": imageBaseUrl + "s_zhukov.png",
    "s_moe": imageBaseUrl + "s_moe.png",
    "s_dd": imageBaseUrl + "s_dd.png",
    "s_sopmod": imageBaseUrl + "s_sopmod.png",
    "s_hunter": imageBaseUrl + "s_hunter.png",
    "s_modx": imageBaseUrl + "s_modx.png",
    "s_arch": imageBaseUrl + "s_arch.png",
    "s_sga": imageBaseUrl + "s_sga.png",
    "mag_30_ar": imageBaseUrl + "mag_30_ar.png",
    "mag_60_ar": imageBaseUrl + "mag_60_ar.png",
    "mag_30_ak": imageBaseUrl + "mag_30_ak.png",
    "mag_60_ak": imageBaseUrl + "mag_60_ak.png",
    "mag_10_svd": imageBaseUrl + "mag_10_svd.png",
    "mag_20_svd": imageBaseUrl + "mag_20_svd.png",
    "mag_ext_9mm": imageBaseUrl + "mag_ext_9mm.png",

    // ==========================================
    // 3. RÜSTUNG, HELME & GEAR
    // ==========================================
    "plate6_plate_carrier": imageBaseUrl + "plate6_plate_carrier.png",
    "phantom_type_2": imageBaseUrl + "phantom_type_2.png",
    "recon_plate_carrier_rpc": imageBaseUrl + "recon_plate_carrier_rpc.png",
    "m2_plate_carrier": imageBaseUrl + "m2_plate_carrier.png",
    "cgpc3_tqs": imageBaseUrl + "cgpc3_tqs.png",
    "chest_rig_901_elite_4": imageBaseUrl + "chest_rig_901_elite_4.png",
    "modular_operator_carrier_gen_ii": imageBaseUrl + "modular_operator_carrier_gen_ii.png",
    "pantsir_2_0": imageBaseUrl + "pantsir_2_0.png",
    "specter": imageBaseUrl + "specter.png",
    "cz_4m_lancer": imageBaseUrl + "cz_4m_lancer.png",
    "cz_4m_lancer_unlra": imageBaseUrl + "cz_4m_lancer_unlra.png",
    "lcs_sentry": imageBaseUrl + "lcs_sentry.png",
    "atbv_schutzweste": imageBaseUrl + "atbv_schutzweste.png",
    "paca_schutzweste": imageBaseUrl + "paca_schutzweste.png",
    "6b2_schutzweste": imageBaseUrl + "6b2_schutzweste.png",
    "fraktions_weste_lri_mss_csi": imageBaseUrl + "fraktions_weste_lri_mss_csi.png",
    "security_weste": imageBaseUrl + "security_weste.png",
    "6b13_1_sturm_panzerung": imageBaseUrl + "6b13_1_sturm_panzerung.png",
    "6b23_1_panzerung": imageBaseUrl + "6b23_1_panzerung.png",
    "6b33_defender_2_schutzweste": imageBaseUrl + "6b33_defender_2_schutzweste.png",
    "wanderer_rucksack_trekstars_70l": imageBaseUrl + "wanderer_rucksack_trekstars_70l.png",
    "delta_rucksack": imageBaseUrl + "delta_rucksack.png",
    "rush_72_2_0": imageBaseUrl + "rush_72_2_0.png",
    "6sh118_ratnik_v2": imageBaseUrl + "6sh118_ratnik_v2.png",
    "falang_28": imageBaseUrl + "falang_28.png",
    "rush_24": imageBaseUrl + "rush_24.png",
    "3_tages_sturmrucksack": imageBaseUrl + "3_tages_sturmrucksack.png",
    "amp12_rucksack": imageBaseUrl + "amp12_rucksack.png",
    "patrouillen_rucksack": imageBaseUrl + "patrouillen_rucksack.png",
    "scorpion_ocp": imageBaseUrl + "scorpion_ocp.png",
    "tagesrucksack_daypack": imageBaseUrl + "tagesrucksack_daypack.png",
    "gunfighter_14": imageBaseUrl + "gunfighter_14.png",
    "sport_rucksack": imageBaseUrl + "sport_rucksack.png",
    "turnbeutel_drawstring_bag": imageBaseUrl + "turnbeutel_drawstring_bag.png",
    "kleiner_touristenrucksack": imageBaseUrl + "kleiner_touristenrucksack.png",
    "lbt_1961a_chest_rig": imageBaseUrl + "lbt_1961a_chest_rig.png",
    "tactec_brust_rig": imageBaseUrl + "tactec_brust_rig.png",
    "recon_chest_rig": imageBaseUrl + "recon_chest_rig.png",
    "viper_chest_rig": imageBaseUrl + "viper_chest_rig.png",
    "training_mini_rig": imageBaseUrl + "training_mini_rig.png",
    "type_81_ak_rig": imageBaseUrl + "type_81_ak_rig.png",
    "type_56_ak_rig": imageBaseUrl + "type_56_ak_rig.png",
    "improvisiertes_rig": imageBaseUrl + "improvisiertes_rig.png",
    "fast_mt_helm": imageBaseUrl + "fast_mt_helm.png",
    "altyn_helm": imageBaseUrl + "altyn_helm.png",
    "exfil_helm_team_wendy": imageBaseUrl + "exfil_helm_team_wendy.png",
    "mich_tc_2000": imageBaseUrl + "mich_tc_2000.png",
    "mich_tc_2002": imageBaseUrl + "mich_tc_2002.png",
    "lshz_1": imageBaseUrl + "lshz_1.png",
    "6b47_ratnik": imageBaseUrl + "6b47_ratnik.png",
    "ssh_68_stahlhelm": imageBaseUrl + "ssh_68_stahlhelm.png",
    "skull_crusher_nvg_mount": imageBaseUrl + "skull_crusher_nvg_mount.png",
    "dschungelhut_boonie_hat": imageBaseUrl + "dschungelhut_boonie_hat.png",
    "baseballkappe_beanie": imageBaseUrl + "baseballkappe_beanie.png",
    "comtac_4_headset": imageBaseUrl + "comtac_4_headset.png",
    "sordin_supreme_pro_x": imageBaseUrl + "sordin_supreme_pro_x.png",
    "comtac_2": imageBaseUrl + "comtac_2.png",
    "earmor_m32": imageBaseUrl + "earmor_m32.png",
    "walker_s_razor": imageBaseUrl + "walker_s_razor.png",
    "gssh_01_headset": imageBaseUrl + "gssh_01_headset.png",
    "gasmaske_gas_mask": imageBaseUrl + "gasmaske_gas_mask.png",
    "sturmhaube_balaclava": imageBaseUrl + "sturmhaube_balaclava.png",
    "shemagh": imageBaseUrl + "shemagh.png",
    "schlauchschal_neck_gaiter": imageBaseUrl + "schlauchschal_neck_gaiter.png",
    "bandana": imageBaseUrl + "bandana.png",
    "taktische_schutzbrille": imageBaseUrl + "taktische_schutzbrille.png",
    "sportsonnenbrille_aviators": imageBaseUrl + "sportsonnenbrille_aviators.png",
    "operator_gürtel_operator_belt": imageBaseUrl + "operator_gürtel_operator_belt.png",
    "gefechtsgürtel_battle_belt": imageBaseUrl + "gefechtsgürtel_battle_belt.png",
    "taktischer_gürtel_tactical_belt": imageBaseUrl + "taktischer_gürtel_tactical_belt.png",
    "dienstgürtel_duty_belt": imageBaseUrl + "dienstgürtel_duty_belt.png",

    // ==========================================
    // 4. LOGISTICS (LOOT & QUESTS)
    // ==========================================
    "ltsd_4_3_laser_zielmarkierer": imageBaseUrl + "ltsd_4_3_laser_zielmarkierer.png",
    "r_438_barrier_t_system": imageBaseUrl + "r_438_barrier_t_system.png",
    "pbg_01_drohnen_kontrollstation": imageBaseUrl + "pbg_01_drohnen_kontrollstation.png",
    "c2_militär_laptop": imageBaseUrl + "c2_militär_laptop.png",
    "strelets_m_tablet": imageBaseUrl + "strelets_m_tablet.png",
    "an_pyq_10": imageBaseUrl + "an_pyq_10.png",
    "kik_11_taktischer_schlüssel_lader": imageBaseUrl + "kik_11_taktischer_schlüssel_lader.png",
    "verstärkter_militär_laptop": imageBaseUrl + "verstärkter_militär_laptop.png",
    "hgcs_30_drohnen_kontrollstation": imageBaseUrl + "hgcs_30_drohnen_kontrollstation.png",
    "robustes_militär_tablet": imageBaseUrl + "robustes_militär_tablet.png",
    "schwarze_kreditkarte": imageBaseUrl + "schwarze_kreditkarte.png",
    "moutai_50_jahre": imageBaseUrl + "moutai_50_jahre.png",
    "platinring": imageBaseUrl + "platinring.png",
    "majestätische_titanuhr": imageBaseUrl + "majestätische_titanuhr.png",
    "diamantring": imageBaseUrl + "diamantring.png",
    "platin_kreditkarte": imageBaseUrl + "platin_kreditkarte.png",
    "diamantohrringe": imageBaseUrl + "diamantohrringe.png",
    "allanach_single_malt_scotch_40_jahre": imageBaseUrl + "allanach_single_malt_scotch_40_jahre.png",
    "diamant_korallen_ring": imageBaseUrl + "diamant_korallen_ring.png",
    "smaragdhalskette": imageBaseUrl + "smaragdhalskette.png",
    "perfekte_perlenohrringe": imageBaseUrl + "perfekte_perlenohrringe.png",
    "aufwendiger_ring": imageBaseUrl + "aufwendiger_ring.png",
    "breda_rum_30_jahre": imageBaseUrl + "breda_rum_30_jahre.png",
    "saphir_anhänger": imageBaseUrl + "saphir_anhänger.png",
    "gold_kreditkarte": imageBaseUrl + "gold_kreditkarte.png",
    "tzuntzimitl_tequila_25_jahre": imageBaseUrl + "tzuntzimitl_tequila_25_jahre.png",
    "elegante_luxusuhr": imageBaseUrl + "elegante_luxusuhr.png",
    "master_carbon_seal_uhr": imageBaseUrl + "master_carbon_seal_uhr.png",
    "dunkle_perlenhalskette": imageBaseUrl + "dunkle_perlenhalskette.png",
    "edelsteinring": imageBaseUrl + "edelsteinring.png",
    "gewöhnliche_kreditkarte": imageBaseUrl + "gewöhnliche_kreditkarte.png",
    "luxus_smartwatch": imageBaseUrl + "luxus_smartwatch.png",
    "goodlad_whiskey_20_jahre": imageBaseUrl + "goodlad_whiskey_20_jahre.png",
    "schlangenwein": imageBaseUrl + "schlangenwein.png",
    "himmlische_parfümflasche": imageBaseUrl + "himmlische_parfümflasche.png",
    "lambert_zigarren": imageBaseUrl + "lambert_zigarren.png",
    "goldhalskette": imageBaseUrl + "goldhalskette.png",
    "zarte_parfümflasche": imageBaseUrl + "zarte_parfümflasche.png",
    "goldring": imageBaseUrl + "goldring.png",
    "moderne_uhr": imageBaseUrl + "moderne_uhr.png",
    "hyperborea_zigaretten": imageBaseUrl + "hyperborea_zigaretten.png",
    "duftende_parfümflasche": imageBaseUrl + "duftende_parfümflasche.png",
    "stange_tahirs_zigaretten": imageBaseUrl + "stange_tahirs_zigaretten.png",
    "tahirs_zigaretten": imageBaseUrl + "tahirs_zigaretten.png",
    "goldkette": imageBaseUrl + "goldkette.png",
    "holzstatue": imageBaseUrl + "holzstatue.png",
    "goldene_uhr_rolex": imageBaseUrl + "goldene_uhr_rolex.png",
    "vip_reisepass": imageBaseUrl + "vip_reisepass.png",
    "touristen_reisepass": imageBaseUrl + "touristen_reisepass.png",
    "einmalpad_schlüsselcodes": imageBaseUrl + "einmalpad_schlüsselcodes.png",
    "biometrische_zugangskarte": imageBaseUrl + "biometrische_zugangskarte.png",
    "biometrischer_usb_stick": imageBaseUrl + "biometrischer_usb_stick.png",
    "armee_geheimdienstdaten": imageBaseUrl + "armee_geheimdienstdaten.png",
    "geschäftsmann_ausweis": imageBaseUrl + "geschäftsmann_ausweis.png",
    "führerschein": imageBaseUrl + "führerschein.png",
    "einheimischen_ausweis": imageBaseUrl + "einheimischen_ausweis.png",
    "verbrechen_bezogene_daten": imageBaseUrl + "verbrechen_bezogene_daten.png",
    "touristen_ausweis": imageBaseUrl + "touristen_ausweis.png",
    "beweise_dokumente_intel": imageBaseUrl + "beweise_dokumente_intel.png",
    "geldautomaten_hacking_tool": imageBaseUrl + "geldautomaten_hacking_tool.png",
    "verschlüsselte_einsatz_festplatte": imageBaseUrl + "verschlüsselte_einsatz_festplatte.png",
    "schwarzes_luxus_smartphone": imageBaseUrl + "schwarzes_luxus_smartphone.png",
    "verschlüsselte_festplatte": imageBaseUrl + "verschlüsselte_festplatte.png",
    "npi_2_navigationsempfänger": imageBaseUrl + "npi_2_navigationsempfänger.png",
    "luxus_smartphone": imageBaseUrl + "luxus_smartphone.png",
    "spiegelreflexkamera_dslr": imageBaseUrl + "spiegelreflexkamera_dslr.png",
    "glonass_grot_m_navigationsempfänger": imageBaseUrl + "glonass_grot_m_navigationsempfänger.png",
    "azart_p1_funkgerät": imageBaseUrl + "azart_p1_funkgerät.png",
    "laptop": imageBaseUrl + "laptop.png",
    "tragbarer_ecm_störsender": imageBaseUrl + "tragbarer_ecm_störsender.png",
    "signalverstärker_rt97s": imageBaseUrl + "signalverstärker_rt97s.png",
    "teures_smartphone": imageBaseUrl + "teures_smartphone.png",
    "smartphone": imageBaseUrl + "smartphone.png",
    "digitalkamera_digicam": imageBaseUrl + "digitalkamera_digicam.png",
    "handy_ladegerät": imageBaseUrl + "handy_ladegerät.png",
    "weißes_lithiumfett": imageBaseUrl + "weißes_lithiumfett.png",
    "werkzeugset": imageBaseUrl + "werkzeugset.png",
    "schwefelsäure": imageBaseUrl + "schwefelsäure.png",
    "kaputte_nagelpistole": imageBaseUrl + "kaputte_nagelpistole.png",
    "autobatterie": imageBaseUrl + "autobatterie.png",
    "acetylenflasche": imageBaseUrl + "acetylenflasche.png",
    "kaputter_winkelschleifer": imageBaseUrl + "kaputter_winkelschleifer.png",
    "kaputte_stichsäge": imageBaseUrl + "kaputte_stichsäge.png",
    "gummi_erneuerer": imageBaseUrl + "gummi_erneuerer.png",
    "aramid_gewebe": imageBaseUrl + "aramid_gewebe.png",
    "motorradbatterie": imageBaseUrl + "motorradbatterie.png",
    "propanflasche": imageBaseUrl + "propanflasche.png",
    "starthilfekabel": imageBaseUrl + "starthilfekabel.png",
    "industrielles_lösungsmittel": imageBaseUrl + "industrielles_lösungsmittel.png",
    "kaputte_handsäge": imageBaseUrl + "kaputte_handsäge.png",
    "minderwertiges_schießpulver": imageBaseUrl + "minderwertiges_schießpulver.png",
    "bremsflüssigkeit": imageBaseUrl + "bremsflüssigkeit.png",
    "benzinkanister": imageBaseUrl + "benzinkanister.png",
    "bleichmittel": imageBaseUrl + "bleichmittel.png",
    "naosaoad_100_reiniger": imageBaseUrl + "naosaoad_100_reiniger.png",
    "motoröl": imageBaseUrl + "motoröl.png",
    "rohrreiniger": imageBaseUrl + "rohrreiniger.png",
    "tarnstoff": imageBaseUrl + "tarnstoff.png",
    "paracord": imageBaseUrl + "paracord.png",
    "waffenöl": imageBaseUrl + "waffenöl.png",
    "packung_aa_batterien": imageBaseUrl + "packung_aa_batterien.png",
    "kaputter_schraubenschlüssel": imageBaseUrl + "kaputter_schraubenschlüssel.png",
    "kaputter_zimmermannshammer": imageBaseUrl + "kaputter_zimmermannshammer.png",
    "kaputter_schraubenzieher": imageBaseUrl + "kaputter_schraubenzieher.png",
    "kupferkabel": imageBaseUrl + "kupferkabel.png",
    "nägel": imageBaseUrl + "nägel.png",
    "panzertape": imageBaseUrl + "panzertape.png",
    "waffenteile": imageBaseUrl + "waffenteile.png",
    "zündkerze": imageBaseUrl + "zündkerze.png",
    "fläschchen_mit_antigenen": imageBaseUrl + "fläschchen_mit_antigenen.png",
    "desinfektionsmittel": imageBaseUrl + "desinfektionsmittel.png",
    "un_medizinwerkzeuge": imageBaseUrl + "un_medizinwerkzeuge.png",
    "insektenspray": imageBaseUrl + "insektenspray.png",
    "blutbeutel_500ml": imageBaseUrl + "blutbeutel_500ml.png",
    "morphin_injektor": imageBaseUrl + "morphin_injektor.png",
    "tourniquet_cat": imageBaseUrl + "tourniquet_cat.png",
    "verbandskasten_ifak": imageBaseUrl + "verbandskasten_ifak.png",
    "wasserproben": imageBaseUrl + "wasserproben.png",
    "packung_premium_kaffee": imageBaseUrl + "packung_premium_kaffee.png",
    "wasserreinigungstabletten": imageBaseUrl + "wasserreinigungstabletten.png",
    "mre_kampfration": imageBaseUrl + "mre_kampfration.png",
    "nachfüllbares_feuerzeug": imageBaseUrl + "nachfüllbares_feuerzeug.png",
    "handspiegel": imageBaseUrl + "handspiegel.png",
    "vaseline_petrolatum": imageBaseUrl + "vaseline_petrolatum.png",
    "kartenspiel": imageBaseUrl + "kartenspiel.png",
    "angelschnur": imageBaseUrl + "angelschnur.png",
    "lampenöl": imageBaseUrl + "lampenöl.png",
    "feuerzeug": imageBaseUrl + "feuerzeug.png",
    "nähzeug": imageBaseUrl + "nähzeug.png",
    "rettungsdecke": imageBaseUrl + "rettungsdecke.png",

    // ==========================================
    // 5. STASH & CONTAINER
    // ==========================================
    "safe_lock_box_2x2": imageBaseUrl + "safe_lock_box_2x2.png",
    "admin_tasche_2x3_admin_pouch": imageBaseUrl + "admin_tasche_2x3_admin_pouch.png",
    "tas_secure_container_3x3": imageBaseUrl + "tas_secure_container_3x3.png",
    "muxxum_waffenkoffer_muxxum_rifle_case": imageBaseUrl + "muxxum_waffenkoffer_muxxum_rifle_case.png",
    "harde_kiste_harde_case": imageBaseUrl + "harde_kiste_harde_case.png",
    "waffenteilkiste_weapon_parts_case": imageBaseUrl + "waffenteilkiste_weapon_parts_case.png",
    "metal_munitionskiste_metal_ammo_box": imageBaseUrl + "metal_munitionskiste_metal_ammo_box.png",
    "mm_munitionskiste_mm_ammo_box": imageBaseUrl + "mm_munitionskiste_mm_ammo_box.png",
    "handgranatenkoffer_hand_grenade_storage_box": imageBaseUrl + "handgranatenkoffer_hand_grenade_storage_box.png",
    "magazinkiste_magazine_crate": imageBaseUrl + "magazinkiste_magazine_crate.png",
    "iv_schutzkoffer_iv_truncase": imageBaseUrl + "iv_schutzkoffer_iv_truncase.png",
    "erste_hilfe_koffer_first_aid_case": imageBaseUrl + "erste_hilfe_koffer_first_aid_case.png",
    "kühlbox_proviantkiste_personal_cooler": imageBaseUrl + "kühlbox_proviantkiste_personal_cooler.png",
    "großer_schlüsselkoffer_huge_key_case": imageBaseUrl + "großer_schlüsselkoffer_huge_key_case.png",
    "mörser_kiste_mortar_round_case": imageBaseUrl + "mörser_kiste_mortar_round_case.png",
    "kleiner_tresor_small_safe": imageBaseUrl + "kleiner_tresor_small_safe.png",
    "großer_tresor_large_safe": imageBaseUrl + "großer_tresor_large_safe.png",
    "verwaltungstisch_administrative_desk": imageBaseUrl + "verwaltungstisch_administrative_desk.png",
    "geldbörse_tactical_wallet": imageBaseUrl + "geldbörse_tactical_wallet.png",
    "lederschlüsselhalter_key_holder": imageBaseUrl + "lederschlüsselhalter_key_holder.png",
    "schlüsseltasche_key_case": imageBaseUrl + "schlüsseltasche_key_case.png",
    "injektoren_etui_injector_case": imageBaseUrl + "injektoren_etui_injector_case.png",
    "verwaltungstasche_administration_bag": imageBaseUrl + "verwaltungstasche_administration_bag.png",
    "kombat_ordner_kombat_folder": imageBaseUrl + "kombat_ordner_kombat_folder.png",
    "hartschalen_erste_hilfe_hfak": imageBaseUrl + "hartschalen_erste_hilfe_hfak.png",
    "mini_erste_hilfe_set_mfak": imageBaseUrl + "mini_erste_hilfe_set_mfak.png",
    "schnellverschluss_medikit_qfak": imageBaseUrl + "schnellverschluss_medikit_qfak.png",
    "rip_away_emt_pouch_emt": imageBaseUrl + "rip_away_emt_pouch_emt.png",
    "locker_erweiterungen_locker_expansions": imageBaseUrl + "locker_erweiterungen_locker_expansions.png",

    // ==========================================
    // 6. MEDICAL CENTER
    // ==========================================
    "encumbered": imageBaseUrl + "encumbered.png",
    "exhausted": imageBaseUrl + "exhausted.png",
    "fatigued": imageBaseUrl + "fatigued.png",
    "sore_arms": imageBaseUrl + "sore_arms.png",
    "cramps": imageBaseUrl + "cramps.png",
    "out_of_breath": imageBaseUrl + "out_of_breath.png",
    "thirsty": imageBaseUrl + "thirsty.png",
    "hungry": imageBaseUrl + "hungry.png",
    "bleed_light": imageBaseUrl + "bleed_light.png",
    "bleed_med": imageBaseUrl + "bleed_med.png",
    "bleed_heavy": imageBaseUrl + "bleed_heavy.png",
    "limping": imageBaseUrl + "limping.png",
    "organ_damage": imageBaseUrl + "organ_damage.png",
    "tremors": imageBaseUrl + "tremors.png",
    "coughing": imageBaseUrl + "coughing.png",
    "upset_stomach": imageBaseUrl + "upset_stomach.png",
    "nauseous": imageBaseUrl + "nauseous.png",
    "dizzy": imageBaseUrl + "dizzy.png",
    "dazed_confused": imageBaseUrl + "dazed_confused.png",
    "vision_blackout": imageBaseUrl + "vision_blackout.png",
    "hurt_pain": imageBaseUrl + "hurt_pain.png",
    "pain": imageBaseUrl + "pain.png",
    "radiation": imageBaseUrl + "radiation.png",
    "coma": imageBaseUrl + "coma.png",

    // ==========================================
    // 7. PROVISIONS (FOOD & WATER)
    // ==========================================
    "dark_star_iced_coffee": imageBaseUrl + "dark_star_iced_coffee.png",
    "nuklear_energy_meltdown_mango": imageBaseUrl + "nuklear_energy_meltdown_mango.png",
    "energy_bar_nuts_and_fruits": imageBaseUrl + "energy_bar_nuts_and_fruits.png",
    "windmill_almond_choc_bar": imageBaseUrl + "windmill_almond_choc_bar.png",
    "tamtam_doublechoc": imageBaseUrl + "tamtam_doublechoc.png",
    "berg_bar_cookie_chocolate": imageBaseUrl + "berg_bar_cookie_chocolate.png",
    "noakon_water_0_6_l": imageBaseUrl + "noakon_water_0_6_l.png",
    "power_energy_drink": imageBaseUrl + "power_energy_drink.png",
    "gray_focused_energy": imageBaseUrl + "gray_focused_energy.png",
    "infinity_isotonic_drink": imageBaseUrl + "infinity_isotonic_drink.png",
    "kaipo_lychee_nectar": imageBaseUrl + "kaipo_lychee_nectar.png",
    "touchdown_lemon_soda": imageBaseUrl + "touchdown_lemon_soda.png",
    "coco_jumbo_coconut_juice": imageBaseUrl + "coco_jumbo_coconut_juice.png",
    "sunrise_cola": imageBaseUrl + "sunrise_cola.png",
    "aques_water_1_l": imageBaseUrl + "aques_water_1_l.png",
    "aques_water_1_5_l": imageBaseUrl + "aques_water_1_5_l.png",
    "noakon_water_1_l": imageBaseUrl + "noakon_water_1_l.png",
    "noakon_water_1_5_l": imageBaseUrl + "noakon_water_1_5_l.png",
    "maknav_iced_tea": imageBaseUrl + "maknav_iced_tea.png",
    "white_orchid_crystal_water_2_l": imageBaseUrl + "white_orchid_crystal_water_2_l.png",
    "riminda_green_bubbly_bliss": imageBaseUrl + "riminda_green_bubbly_bliss.png",
    "sunrise_cola_2_l": imageBaseUrl + "sunrise_cola_2_l.png",
    "spicy_thai_combat_meal": imageBaseUrl + "spicy_thai_combat_meal.png",
    "combat_ration_pack_crp": imageBaseUrl + "combat_ration_pack_crp.png",
    "hdr_meal": imageBaseUrl + "hdr_meal.png",
    "premium_pork_luncheon_meat": imageBaseUrl + "premium_pork_luncheon_meat.png",
    "sinngua_lunch_meat": imageBaseUrl + "sinngua_lunch_meat.png",
    "mackerel_in_teriyaki_sauce": imageBaseUrl + "mackerel_in_teriyaki_sauce.png",
    "canned_tuna_chunks": imageBaseUrl + "canned_tuna_chunks.png",
    "cowboy_baked_beans": imageBaseUrl + "cowboy_baked_beans.png",
    "lucky_pork_liver_p_t_": imageBaseUrl + "lucky_pork_liver_p_t_.png",
    "lychee_in_syrup": imageBaseUrl + "lychee_in_syrup.png",
    "organic_tofu": imageBaseUrl + "organic_tofu.png",
    "1_shot_energy_chews": imageBaseUrl + "1_shot_energy_chews.png",
    "bamboo_shoots": imageBaseUrl + "bamboo_shoots.png",
    "kasem_chocolate_wafers": imageBaseUrl + "kasem_chocolate_wafers.png",
    "snipsnap_crunchy": imageBaseUrl + "snipsnap_crunchy.png"
};

// ==============================================================
// TACTICAL HOVER ENGINE (BILDER-OVERLAY) LOGIK
// ==============================================================
// Diese Logik kann hier in der Datei stehen und wird automatisch
// aktiv, sobald die Datei in deiner index.html geladen wird.

document.addEventListener('mouseover', function(e) {
    let target = e.target.closest('.item-hover-trigger');
    if (target) {
        let rawId = target.getAttribute('data-item-id');
        if (!rawId) return;

        // Macht den Namen "Safe Lock Box (2x2)" zu "safe_lock_box_2x2"
        let formattedId = rawId.toLowerCase()
                               .replace(/[^a-z0-9]+/g, "_")
                               .replace(/^_|_$/g, "");

        if (typeof itemImages !== 'undefined' && itemImages[formattedId]) {
            let tooltip = document.getElementById('tacticalImageTooltip');
            if(tooltip) {
                let img = document.getElementById('tacticalTooltipImg');
                img.src = itemImages[formattedId];
                tooltip.style.display = 'block';
            }
        }
    }
});

document.addEventListener('mousemove', function(e) {
    let tooltip = document.getElementById('tacticalImageTooltip');
    if (tooltip && tooltip.style.display === 'block') {
        tooltip.style.left = (e.pageX + 15) + 'px';
        tooltip.style.top = (e.pageY + 15) + 'px';
    }
});

document.addEventListener('mouseout', function(e) {
    let target = e.target.closest('.item-hover-trigger');
    if (target) {
        let tooltip = document.getElementById('tacticalImageTooltip');
        if(tooltip) {
            tooltip.style.display = 'none';
            document.getElementById('tacticalTooltipImg').src = '';
        }
    }
});
